# Generated by Django 5.2.2 on 2025-06-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0002_user_details_confpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
