# Generated by Django 5.2.2 on 2025-06-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0008_remove_task_emp_order_status_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
